"""
Channel Content — Pinned messages, descriptions, and guide posts for Telegram channels.
Run this to send all content to both channels via the bot.

Usage:
    python channel_content.py --preview          # print all messages (don't send)
    python channel_content.py --send-pulse       # send to Fleet Pulse
    python channel_content.py --send-intel       # send to Fleet Intelligence
    python channel_content.py --send-all         # send to both + pin
    python channel_content.py --set-descriptions # set channel descriptions via API
"""

import json
import sys
import time
import urllib.request
import urllib.error

try:
    from fleet_config import bot_registry_list
except ImportError:  # pragma: no cover — CC always has it on the path
    bot_registry_list = None


def _fleet_size() -> int:
    """Pollable fleet members, from the one source of truth.

    These strings become the live Telegram channel descriptions, so a
    hardcoded count is a subscriber-facing claim that goes stale silently —
    the same defect as the "19 bots · live" literal on the signal cards
    (fixed 2026-08-05). It said 16 while the roster had 18.

    Falls back to 18 only if the registry is unavailable; that is a wrong
    number in a failure case, but the alternative is a broken publish.
    """
    if bot_registry_list is None:
        return 18
    try:
        return len(bot_registry_list()) or 18
    except Exception:
        return 18


def _pair_count() -> int:
    """Trading pairs in the live universe. Same reasoning as _fleet_size():
    this is subscriber-facing copy, and the hardcoded 47 was stale (50 live).
    """
    try:
        import os
        u = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                        "universe.json"), encoding="utf-8"))
        n = u.get("count")
        if isinstance(n, int) and n > 0:
            return n
        pairs = u.get("pairs")
        if isinstance(pairs, (list, dict)) and pairs:
            return len(pairs)
    except Exception:
        pass
    return 50


_N = _fleet_size()
_PAIRS = _pair_count()

with open("signal_config.json") as f:
    CFG = json.load(f)

TOKEN = CFG["telegram_bot_token"]
FREE_CHAT = CFG["telegram_free_chat_id"]
PAID_CHAT = CFG["telegram_paid_chat_id"]

# ══════���════════════════════════════════════════════════════════════════════════
# CHANNEL DESCRIPTIONS (set via setChatDescription API)
# Max 255 chars each
# ════════���═════════════════���════════════════════════════════════════════════════

FREE_DESCRIPTION = (
    f"Live signals from a {_N}-bot AI trading fleet.\n"
    "Whale alerts · regime shifts · trade entries · risk events\n"
    "All real. All live. Updated 24/7.\n\n"
    "Full analysis + bot details → DM @OracleQNTMCoreBot"
)

# Private channel — no username, but description still shows to members
PAID_DESCRIPTION = (
    f"GoldenEye Intelligence — full signal feed from a {_N}-bot AI trading fleet.\n"
    "Entry/exit prices · position sizes · physics engine analysis · fleet health breakdown\n\n"
    "Free preview → @goldeneye_fleet_pulse"
)

# ════════════════���════════════════════���═════════════════════════════════════════
# PINNED WELCOME MESSAGE — FLEET PULSE (FREE)
# ═════���═══════════════════���═════════════════════════════��═══════════════════════

FREE_WELCOME = f"""<b>Welcome to Fleet Pulse</b>

You're watching a live trading fleet.

{_N} bots. {_PAIRS} trading pairs. 13 mathematical engines scanning the market around the clock. Every signal you see here is real — generated by algorithms that are actually managing capital, not some guy drawing lines on a chart.

<b>What you'll see here:</b>

🔵 <b>Trade alerts</b> — when we open or close a position, you'll know the pair, the direction, and the result. We don't hide our losses.

🟠 <b>Whale alerts</b> — when a large player moves on a pair, we flag it.

🟣 <b>Regime changes</b> — when the market character shifts (trending → ranging → volatile), the fleet adapts. You'll see it happen in real time.

🟣 <b>Fleet health</b> — our risk system continuously monitors conditions. When it flags danger, we cut exposure. You'll see those calls too.

🟡 <b>Liquidity alerts</b> — when an order book falls apart, we warn you before you step into a bad fill.

🔴 <b>Emergency events</b> — if stops cascade and the fleet goes to cash, you'll see it immediately.

<b>What's the catch?</b>

You're seeing the signal and the pair, but not the full picture. Entry prices, position sizes, which bot pulled the trigger, the math behind the call, the component breakdown of our risk scores — that's in GoldenEye Intelligence.

Think of Pulse as the scoreboard. Intelligence is the locker room.

🔒 <b>Upgrade:</b> Message @OracleQNTMCoreBot for access to the full feed.

<i>Signals are generated by autonomous trading algorithms. This is not financial advice. Always do your own research.</i>"""

# ══════════════════════════��════════════════════════════════════════════════════
# PINNED WELCOME MESSAGE — FLEET INTELLIGENCE (PAID)
# ═════════════════��════════════════════════════════════��════════════════════════

PAID_WELCOME = f"""<b>Welcome to GoldenEye Intelligence</b>

You have the full feed. Everything the fleet sees, you see.

<b>What you get that Pulse doesn't:</b>

▪ <b>Entry & exit prices</b> — exact levels, not just "we opened a trade"
▪ <b>Position sizes</b> — how much capital we committed and why
▪ <b>Bot identification</b> — which system pulled the trigger
▪ <b>Risk breakdown</b> — the health score isn't just a number, you get every component: what's dragging it down, which bots disagree, where the stress is
▪ <b>Physics engine analysis</b> — 13 mathematical models scan market structure around the clock. You get the plain-English interpretation of what each one finds
▪ <b>Lead-lag relationships</b> — when one asset is leading another, you'll know the delay and the strength
▪ <b>Price levels</b> — key support/resistance with strength scores and distance
▪ <b>Live fleet context</b> — every card shows the current price, fleet regime, risk status, and deployment in one line

<b>How to read the cards:</b>

Every signal has three parts:
1. <b>The headline</b> — what happened, one line
2. <b>The reasoning</b> — why it matters, in plain English (the italic text)
3. <b>The data</b> — the numbers, with progress bars so you can read them at a glance

The progress bars: ▓▓▓▓▓░░░░░ — filled = signal strength. More filled = stronger signal.

<b>Signal types from most to least urgent:</b>

🔴 <b>Red</b> — Emergency, unpredictable market, sudden move warning. Act or get out of the way.
🟡 <b>Yellow</b> — Caution. Liquidity issues, regime shifting, key level approaching. Pay attention.
���� <b>Purple</b> — Regime / fleet posture. The market changed character. Adjust your expectations.
🟠 <b>Orange</b> — Whale activity. Big money is moving. Watch the pair.
🟢 <b>Green</b> — Signal or conviction. Something looks good. Opportunity.
🔵 <b>Blue</b> — Position opened, new trend forming. We're in.
⚪ <b>White</b> — Position closed. We're out. Check the P/L.

<b>The fleet context line</b> (bottom of paid cards):
<code>BTC/USD $71,524 · ⚠ CAUTIOUS · Risk ✅ GREEN · Deployed 0% · {_N} bots</code>
That's the whole fleet state in one glance.

<i>Signals are generated by autonomous trading algorithms. This is not financial advice. Past performance does not guarantee future results.</i>"""

# ═════���══════════���═════════════════════════════���════════════════════════════════
# SIGNAL GUIDE POST — FLEET PULSE (explains each signal type for newcomers)
# ═════════════��═════════════════════════════��═══════════════════════════════════

FREE_GUIDE = """<b>📖 What Do These Signals Mean?</b>

Quick reference for everything you'll see in this channel:

<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>

🔵 <b>POSITION OPENED</b>
<i>The fleet just entered a trade. You'll see the pair (like BTC/USD) and direction (LONG = betting it goes up, SHORT = betting it goes down).</i>

⚪ <b>POSITION CLOSED</b>
<i>A trade was exited. ✔ WIN means profit, ✖ LOSS means controlled loss. We show both — no hiding.</i>

🟢 <b>HIGH CONVICTION</b>
<i>Multiple independent bots agree on one trade. The more bots that agree, the stronger the signal historically.</i>

🟠 <b>WHALE ALERT</b>
<i>A very large buyer or seller appeared on an exchange. Think of it as seeing a billionaire walk into a store — the price might move.</i>

🟣 <b>MARKET SHIFT</b>
<i>The type of market just changed — trending, ranging, volatile, etc. This changes how the fleet trades (and how you should think about risk).</i>

🟣 <b>FLEET HEALTH CHECK</b>
<i>Our risk system rates overall conditions. High score = good conditions, we deploy more. Low score = stressed, we hold cash.</i>

🟡 <b>LIQUIDITY CRISIS / WARNING</b>
<i>The order book is thin or broken. If you trade that pair right now, you'll probably get bad fills.</i>

🔴 <b>EMERGENCY</b>
<i>Something went wrong fast. The fleet is closing everything. This is our fire alarm.</i>

<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>

<b>What does "▲ LONG" and "▼ SHORT" mean?</b>

▲ LONG = We think the price will go up, so we bought.
▼ SHORT = We think the price will go down, so we sold.

<b>What's the 🔒?</b>

Some details (entry prices, bot names, position sizes, full risk analysis) are only available in GoldenEye Intelligence — our premium feed.

Message @OracleQNTMCoreBot for access.

<i>Not financial advice. Signals from autonomous algorithms. DYOR.</i>"""


# ��═════════════════════════════════════════════════════════════���════════════════
# SEND LOGIC
# ════════════════════════════════════════════════════════════���══════════════════

def send_message(chat_id: str, text: str, pin: bool = False) -> dict | None:
    """Send a Telegram message and optionally pin it."""
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = json.dumps({
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "HTML",
        "disable_web_page_preview": True,
    }).encode("utf-8")
    try:
        req = urllib.request.Request(url, data=payload,
                                     headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
            msg_id = result.get("result", {}).get("message_id")
            print(f"  ✓ Sent (msg_id={msg_id})")

            if pin and msg_id:
                time.sleep(1)
                pin_url = f"https://api.telegram.org/bot{TOKEN}/pinChatMessage"
                pin_payload = json.dumps({
                    "chat_id": chat_id,
                    "message_id": msg_id,
                    "disable_notification": True,
                }).encode("utf-8")
                pin_req = urllib.request.Request(pin_url, data=pin_payload,
                                                 headers={"Content-Type": "application/json"})
                urllib.request.urlopen(pin_req, timeout=10)
                print(f"  📌 Pinned")

            return result
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"  ✗ HTTP {e.code}: {body[:200]}")
        return None
    except Exception as e:
        print(f"  ✗ Error: {e}")
        return None


def set_description(chat_id: str, description: str) -> bool:
    """Set a channel's description."""
    url = f"https://api.telegram.org/bot{TOKEN}/setChatDescription"
    payload = json.dumps({
        "chat_id": chat_id,
        "description": description,
    }).encode("utf-8")
    try:
        req = urllib.request.Request(url, data=payload,
                                     headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=10)
        print(f"  ✓ Description set")
        return True
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"  ✗ HTTP {e.code}: {body[:200]}")
        return False
    except Exception as e:
        print(f"  ✗ Error: {e}")
        return False


def preview():
    print("=" * 60)
    print("FREE CHANNEL DESCRIPTION:")
    print(FREE_DESCRIPTION)
    print()
    print("=" * 60)
    print("PAID CHANNEL DESCRIPTION:")
    print(PAID_DESCRIPTION)
    print()
    print("=" * 60)
    print("FREE WELCOME (pinned):")
    print(FREE_WELCOME)
    print()
    print("=" * 60)
    print("PAID WELCOME (pinned):")
    print(PAID_WELCOME)
    print()
    print("=" * 60)
    print("FREE SIGNAL GUIDE:")
    print(FREE_GUIDE)


def main():
    args = sys.argv[1:] if len(sys.argv) > 1 else ["--preview"]

    if "--preview" in args:
        preview()
        return

    if "--set-descriptions" in args or "--send-all" in args:
        print("\n📋 Setting channel descriptions...")
        print("Fleet Pulse:")
        set_description(FREE_CHAT, FREE_DESCRIPTION)
        time.sleep(1)
        print("Fleet Intelligence:")
        set_description(PAID_CHAT, PAID_DESCRIPTION)
        time.sleep(1)

    if "--send-pulse" in args or "--send-all" in args:
        print("\n📨 Sending to Fleet Pulse...")
        print("Welcome message:")
        send_message(FREE_CHAT, FREE_WELCOME, pin=True)
        time.sleep(2)
        print("Signal guide:")
        send_message(FREE_CHAT, FREE_GUIDE)
        time.sleep(1)

    if "--send-intel" in args or "--send-all" in args:
        print("\n📨 Sending to Fleet Intelligence...")
        print("Welcome message:")
        send_message(PAID_CHAT, PAID_WELCOME, pin=True)
        time.sleep(1)

    print("\n✓ Done")


if __name__ == "__main__":
    main()
